# LosgisticRegression

In [7]:
import numpy as np
import pandas as pd
from sklearn.linear_model  import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv('table_total_index.csv')

X = df.drop('label',axis=1)
y = df['label']

X.head(3)


record  location  compromise  content  education  mindset  financial  \
0       1         0           0        2          0        0          0   
1       0         1           0        0          0        0          0   
2       0         0           0        0          0        0          0   

   support  attitude  confess  sequel  crime  
0        0         0        0       0      0  
1        1         2        0       0      0  
2        0         0        0       0      0

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

model=LogisticRegression(multi_class = 'multinomial') 
model.fit(X_train,y_train)

X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)

print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('confusion matrix: {}'.format(con_matrix))



number of correct sample: 19
accuracy: 0.475
confusion matrix: [[1 0 0 1 1 1 0 0 2 0]
 [0 5 0 0 0 0 0 0 0 0]
 [0 1 2 0 1 0 0 1 0 0]
 [1 0 0 2 0 0 0 0 0 0]
 [0 1 0 0 2 0 1 0 1 0]
 [0 1 0 1 0 1 0 0 0 0]
 [0 0 1 0 2 0 2 0 0 0]
 [0 1 0 0 0 0 0 2 1 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 1 0 0 0 0 1 0]]
