# K-Nearest Neighbor

In [2]:
import numpy as np
import pandas as pd
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
df = pd.read_csv('./JudgeTest.csv')
df.head(3)


record  location  compromise  content  education  mindset  financial  \
0       1         0           0        2          0        0          0   
1       0         1           0        0          0        0          0   
2       0         0           0        0          0        0          0   

   support  attitude  confess  sequel  crime  label  
0        0         0        0       0      0      9  
1        1         2        0       0      0      9  
2        0         0        0       0      0      7

In [123]:
X = df.drop('label',axis=1)
y = df['label']

scaler = preprocessing.StandardScaler().fit(X)
X = scaler.transform(X)

In [124]:
# 設定要調整的參數
parameters = {'algorithm':('auto', 'ball_tree', 'kd_tree', 'brute'),'weights' :('uniform','distance'),'n_neighbors':list(range(1,21)),'p':list(range(1,11))}
# 建立空模
model = neighbors.KNeighborsClassifier()
# 將空模跟參數餵進GridSearchCV
clf = GridSearchCV(model, parameters)
# 餵data
clf.fit(X, y)
# 印出最佳參數
print(clf.best_estimator_)
print(clf.best_params_)
print(clf.best_score_)
# 看詳細result
#pd.DataFrame(clf.cv_results_)

KNeighborsClassifier(algorithm='brute', n_neighbors=3, p=1, weights='distance')
{'algorithm': 'brute', 'n_neighbors': 3, 'p': 1, 'weights': 'distance'}
0.6879487179487179


In [39]:
X = df.drop('label',axis=1)
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# bestK = 0
# bestP = 0
# bestScore = 0

# for k in range(1, 20):
#     for p in range(1, 10):
#         model = neighbors.KNeighborsClassifier(weights = 'distance', n_neighbors = k, p = p)
#         model.fit(X_train, y_train)
#         score = model.score(X_test, y_test)
#         if score > bestScore:
#             bestK = k
#             bestP = p
#             bestScore = score
            
# print('bestK:', bestK)
# print('bestP:', bestP)
# print('bestScore:', bestScore)

bestK: 2
bestP: 1
bestScore: 0.85


In [182]:
X = df.drop('label',axis=1)
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)


model = neighbors.KNeighborsClassifier(algorithm = 'brute', n_neighbors = 3, weights = 'distance', p = 1)
# model = neighbors.KNeighborsClassifier(n_neighbors = 4, weights = 'distance', p = 1)
model.fit(X_train, y_train)

X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
score = model.score(X_test, y_test)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)

print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('score: {}'.format(score))
print('confusion matrix: {}'.format(con_matrix))


number of correct sample: 30
accuracy: 0.75
score: 0.75
confusion matrix: [[2 0 2 0 0 0 1 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0]
 [0 0 1 0 2 0 0 0 0 0]
 [1 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [1 0 1 0 1 0 0 0 3 0]
 [0 0 0 0 0 0 0 2 0 1]]
